version: '3'
services:
  rffes:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/aprrp
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload